In [ ]:
# numpy==> numpy is a open source librabry that is used for sccintific calculation

In [ ]:
# why we use numpy whenevefr we have list?
# (1).homogeneus data type
# (2).memory less consume
# (3).less time consume

In [ ]:
# !pip install numpy

In [1]:
import numpy as np

In [3]:
a=[1,2,3,4]
type(a)

list

In [4]:
b=np.array(a)
b

array([1, 2, 3, 4])

In [5]:
type(b)

numpy.ndarray

In [ ]:
# dimension ==>
# 1-d==>element exist in x- direction
# 2-d==>element exist in x and y direction
# 3-d==>element exist in x,y,z direction


In [7]:
print("total shape:",b.shape) ## shape=n(rows),n(columns)

total: (4,)


In [8]:
print("total elements:",b.size) ## shape=n(row)*n(column)

total elements: 4


In [9]:
print("total dimention:",b.ndim)

total dimention: 1


In [10]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
type(b)

numpy.ndarray

In [13]:
print("total rows and colums",b.shape)
print("total elements",b.size)
print("total dimension",b.ndim)

total rows and colums (3, 3)
total elements 9
total dimension 2


In [16]:
# how can we create a user defined arary
a=[]
size=int(input("enter size:"))
for i in range(size):
    val=int(input("enter number"))
    a.append(val)
b=np.array(a)
b
    

enter size:3
enter number1
enter number2
enter number3


array([1, 2, 3])

In [ ]:
# numpy functions
# images==>pixels(0-255)px==>0px(black),255px(white)==>normalize==>(0-1)px
# (a).black&white==> hight,width
# (b).colorfull image==>height,width,color_channel(red,green,blue)
# matrix==>n(rows)=n(columns)==>sumatric matrix,n(r)!=n(c)==>asymatrix matrix
# random number generation ==> random module
# data science==>simple line equation =y=mx+b ##(x,y)=co-

In [18]:
# (1).zeros==>it will create an arary in which all the values are 0
a=np.zeros(3)
a

array([0., 0., 0.])

In [19]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# (2).ones()==> it will create an array in which all the values are 1
a=np.ones(3)
a

array([1., 1., 1.])

In [22]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
a.shape

(3, 4)

In [25]:
# (3).eye()==>it will create an array in which digonal positional element are 1 and reat all are 0
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
a=np.eye(3,4)## asymatric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [27]:
# (4).diag()==>it will create an array in which we can customize our diagonal positional elements
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# (5).randome module ==>
# (a).otp generation
# (b).dataset==> 1 dummy column add
# (c).randomly weight initialize


In [ ]:
# (a).randint(min_number,max_number,total_number)


In [28]:
a=np.random.randint(1,10,3)
a

array([6, 6, 6])

In [9]:
a=np.random.rand(10)
a

array([0.63011617, 0.83119826, 0.72602202, 0.78660241, 0.75892606,
       0.0926386 , 0.09234297, 0.05110654, 0.82567679, 0.76223996])

In [30]:
# (c).randn()==>-3 to +3
a=np.random.randn(5)
a

array([-0.57986348, -0.65713876, -1.91893955, -0.13987788, -1.21928273])

In [35]:
# (d).seed()==it will fix our data once the data has been generate
np.random.seed(1)
a=np.random.randint(1,10,3)
a

array([6, 9, 6])

In [3]:
# view vs copy
a=np.array([10,20,30,40,50,60,70,80]) ## view means modification in orirginal data.
b=a[2:5]
b[:]=0
a

array([10, 20,  0,  0,  0, 60, 70, 80])

In [4]:
a=np.array([10,20,30,40,50,60,70,80]) ##copy() means modification in duplicate file .
b=a[2:5].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
# reshaping and data
# we know that 
# n(nows)*n(colums)=n(total_elements)
# if we have total_elements=12
# 1*2,12*1
# 2*6,6*2
# 3**4,4*3

# if we have total_elements =36
# 1*36,36*1
# 2*18,18*2
# 3*12,12*3
# 4*9,9*4
# 6*6


In [5]:
a=np.random.randint(1,50,12)
a

array([11, 38, 30, 26, 10, 10,  2, 33, 35, 13, 19, 45])

In [6]:
a.shape

(12,)

In [9]:
a.reshape(3,4)

array([[11, 38, 30, 26],
       [10, 10,  2, 33],
       [35, 13, 19, 45]])

In [10]:
a=np.random.randint(1,100,72)
a

array([78, 21, 82, 42, 19, 21, 70, 38, 90,  2, 46, 29, 99, 49, 81, 47,  3,
       73, 44, 92, 98, 92, 67, 78, 20, 28, 74, 28, 66, 42, 16,  4,  6, 47,
       11, 29, 43, 40, 17, 52, 18, 91, 99, 24, 63, 31, 16, 83,  7,  3, 56,
       38, 35,  6, 66, 10, 72, 97, 10, 14, 59, 96, 75,  7, 93, 80, 95, 27,
       40, 18, 48, 82])

In [11]:
a.reshape(8,9)

array([[78, 21, 82, 42, 19, 21, 70, 38, 90],
       [ 2, 46, 29, 99, 49, 81, 47,  3, 73],
       [44, 92, 98, 92, 67, 78, 20, 28, 74],
       [28, 66, 42, 16,  4,  6, 47, 11, 29],
       [43, 40, 17, 52, 18, 91, 99, 24, 63],
       [31, 16, 83,  7,  3, 56, 38, 35,  6],
       [66, 10, 72, 97, 10, 14, 59, 96, 75],
       [ 7, 93, 80, 95, 27, 40, 18, 48, 82]])

In [12]:
a.reshape(12,6)

array([[78, 21, 82, 42, 19, 21],
       [70, 38, 90,  2, 46, 29],
       [99, 49, 81, 47,  3, 73],
       [44, 92, 98, 92, 67, 78],
       [20, 28, 74, 28, 66, 42],
       [16,  4,  6, 47, 11, 29],
       [43, 40, 17, 52, 18, 91],
       [99, 24, 63, 31, 16, 83],
       [ 7,  3, 56, 38, 35,  6],
       [66, 10, 72, 97, 10, 14],
       [59, 96, 75,  7, 93, 80],
       [95, 27, 40, 18, 48, 82]])

In [13]:
# conditional selection in numpy
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
a>16

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [15]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [17]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [18]:
c=a<=10
a[c]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [23]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [25]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [28]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [29]:
a+b

array([[10, 12],
       [14, 16]])

In [30]:
a-b

array([[0, 0],
       [0, 0]])

In [31]:
a.dot(b)

array([[ 67,  78],
       [ 91, 106]])

In [32]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.sum(a)

45

In [34]:
np.sum(a,axis=1) ## row wise total

array([ 6, 15, 24])

In [35]:
np.sum(a,axis=0) ## column wise total

array([12, 15, 18])

In [36]:
# unique()==> it will return unique values or eliminate dublicate values
# it will return 3 array
# (1).unique value of array
# (2).indexing of original value
# (3).returns requancy of each unique values
a=np.array([1,2,2,2,3,4,3,3,3,5,6])
a

array([1, 2, 2, 2, 3, 4, 3, 3, 3, 5, 6])

In [37]:
np.unique(a,return_index=True,return_counts=True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  4,  5,  9, 10], dtype=int64),
 array([1, 3, 4, 1, 1, 1], dtype=int64))

In [39]:
# linespace()==> it will create an arary in which diffrence of each value will be equal
a=np.linspace(1,2,5)
a


array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [41]:
# stacking in numpy 
# (1).hstack()=it will combined multiple array into horizontally
a=np.arange(1,15)
b=np.arange(5,9)
c=np.arange(9,13)

In [42]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  5,  6,  7,
        8,  9, 10, 11, 12])

In [50]:
# (2).vstack()==>it will  combined multiple arrays into vertically
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)

In [52]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])